# OpenData bootstrap configuration
application.version=3.0.0-GUI
application.use-database-properties=true
database.url=jdbc:sqlserver://localhost;databaseName=OpenData;encrypt=true;trustServerCertificate=true
database.user=OpenData
database.password={enc}r5bBcEduLhqoe9+uccsMIwvcneQ7U8ikFC3P1RwOwrUNGPBODWRNtqtKdfm4ZvzEosPKKKqTWgAXudIyJxHzvdvAlDohUvAcNT4C6L8Wokyzi7AM38z4kkpTkJxkRyBArtU5UtGYF6vRvJcuPIa62st4ghX3Dsr9nAzJnKl46CFqk2Vn664LX2dIrfLZa2wPDnCyKzhzZq2Ij5CkUI8rAvjPGL+2QKxO1uIXTwO/RQHCTtGzhlzqhmZkqw51sElU9lvvKGpe3zNoyMYxz0ySv5o6hsARq6GNdX7nAPJoedByhL8X6VzmSPmLEHh/kNoEr2DKfM6GS5lzVor4DbTFXQ==
