# OpenData bootstrap configuration
application.name=OpenData
application.version=2.1.0
application.use-database-properties=true
database.url=jdbc:sqlserver://localhost;databaseName=OpenData;encrypt=true;trustServerCertificate=true
database.user=OpenData
database.password=OpenData
