# OpenData bootstrap configuration
application.version=2.0.0
application.use-database-properties=true
database.url=jdbc:sqlserver://localhost;databaseName=OpenData;encrypt=true;trustServerCertificate=true
database.user=OpenData
database.password={enc}Kq7GbJR5irksRrjA+BHWbyh3bJgdvNouLdnI3R2i7fJoOgLg2uHj5J99x/eqmYg5Z5PtCahsGTyD1Lok90l6pt6Yd65Q0QrO6RGIksoXY3MBmpMQW9cY9ihgrZZpGqhqb5/ljfmLPctCnLFCKs3J09+HeI8ViymUs4/l19EZ2n8kQa3ZcRrSCRS17VlnBV/MMzNDHrovdqhgWDj4EcM3R1ePPSyDVDb7M5yXn4EJK5f7Fjr/8quMQOo5SpFSAaStoGANK7AlVMld5h55Dpt+4Oc5UhK6lI5/XpwkU6K8A2o9mUyDXZ4O5vCoElDE+MgVvrsfwsJXdSiLqIrnefzBQA==
